version: '{build}-{branch}'

branches:
  # whitelist
  only:
    - master

# don't enable for charm
#clone_depth: 50


init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\$env:TARGET\craft\bin\craft.py" $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --branch v0.2.2 --depth=1 git://anongit.kde.org/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & C:\python36\python.exe C:\CraftMaster\CraftMaster\CraftMaster.py --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET
    craft -p charm
    craft nsis
    craft --install-deps charm

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER charm

test_script:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test charm

on_success:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --package charm

on_finish:
- ps: |
    Get-ChildItem $env:USERPROFILE\.craft\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

environment:
    matrix:
    - TARGET: windows-msvc2015_32-cl
    - TARGET: windows-mingw_32-gcc
    - TARGET: windows-msvc2017_64-cl
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
